# Generated by Django 4.2.4 on 2023-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='Address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stud',
            name='Contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stud',
            name='Email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
